import { NextResponse } from 'next/server';
import type { DashboardResponse } from '@/lib/types';

export async function GET() {
  // HARDCODED MOCK DATA - bypass Supabase completely for now
  const mockData: DashboardResponse = {
    next_class: {
      id: 'class-001',
      subject_id: 'subj-fra',
      week: 1,
      day_of_week: 'Monday',
      time_slot: '09:00 AM - 10:30 AM',
      room: 'Lab 101',
      professor: 'Dr. Patel',
      status: 'scheduled',
      calendar_event_id: 'evt-001',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      user_id: 'test-user',
      subject: {
        code: 'FRA',
        name: 'Financial Risk Analysis',
        credits: 3,
      },
    },
    token_vault: [
      {
        id: 'subj-fra',
        user_id: 'test-user',
        code: 'FRA',
        name: 'Financial Risk Analysis',
        credits: 3,
        max_bunks_allowed: 2,
        bunks_used: 0,
        tokens_remaining: 2,
        tokens_max: 2,
        attended_count: 8,
        total_sessions: 10,
        status: 'abundant',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'subj-haw',
        user_id: 'test-user',
        code: 'HAW',
        name: 'Heritage and Wisdom',
        credits: 1,
        max_bunks_allowed: 1,
        bunks_used: 0,
        tokens_remaining: 1,
        tokens_max: 1,
        attended_count: 9,
        total_sessions: 10,
        status: 'caution',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'subj-marketing',
        user_id: 'test-user',
        code: 'MKT',
        name: 'Strategic Marketing',
        credits: 2,
        max_bunks_allowed: 3,
        bunks_used: 1,
        tokens_remaining: 2,
        tokens_max: 3,
        attended_count: 8,
        total_sessions: 10,
        status: 'caution',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    pending_tasks: {
      urgent: [
        {
          id: 'task-001',
          user_id: 'test-user',
          type: 'assignment',
          title: 'FRA Case Study - Risk Modeling',
          description: 'Complete risk model for 3 companies',
          status: 'in_progress',
          deadline: '2026-07-28',
          quality_score: 65,
          comprehension_level: 3,
          subject_id: 'subj-fra',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
      momentum: [
        {
          id: 'task-002',
          user_id: 'test-user',
          type: 'lecture_note',
          title: 'Marketing Fundamentals - Week 1 Notes',
          description: 'Comprehensive lecture notes',
          status: 'completed',
          deadline: '2026-07-25',
          quality_score: 92,
          comprehension_level: 5,
          subject_id: 'subj-marketing',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    gold_medal_status: {
      earned_cgpa: 8.9,
      projected_cgpa: {
        low: 9.2,
        high: 9.5,
      },
      target_cgpa: 9.6,
      gap: {
        low: -0.4,
        high: -0.1,
        status: 'at_risk',
      },
      mastery_percent: 68,
      execution_risk: 'medium',
      data_status: 'current',
      last_updated: new Date().toISOString(),
    },
  };

  return NextResponse.json(mockData);
}
